class NodeWrapper:
    index: int
    color: int
    neighbors: list[int]

    def __init__(
        self, index: int, color: int, neighbors: list[int]
    ) -> None: ...
    def __repr__(self) -> str: ...

class Graph:
    def __init__(self, size: int) -> None: ...
    @classmethod
    def from_edges(cls, edges: list[tuple[int, int]]) -> Graph: ...
    @property
    def nodes(self) -> list[NodeWrapper]: ...
    @property
    def node_map(self) -> dict[int, NodeWrapper]: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def active_ratio(self) -> float: ...
    def are_neighbors(self, i: int, j: int) -> bool: ...
    def next_node(self) -> NodeWrapper: ...
    def next_index(self) -> int: ...
    def copy_remove(self, node_idx: int) -> Graph: ...
    def copy_branch(self, node_idx: int) -> Graph: ...

class DSatur:
    def __init__(self, graph: Graph) -> None: ...
    def solve(self) -> None: ...
    def resolve(self) -> None: ...
    @property
    def cost(self) -> int: ...
    @property
    def bound(self) -> int: ...
    @property
    def max_saturation(self) -> int: ...
