from bnbprob.maxclique.graph import Graph, NodeWrapper
from bnbpy.cython.problem import Problem

class MaxClique(Problem):
    def __init__(self, graph: Graph) -> None: ...
    @property
    def clique(self) -> list[NodeWrapper]: ...
    @property
    def graph(self) -> Graph: ...
    def calc_bound(self) -> float: ...
    def is_feasible(self) -> bool: ...
    def branch(self) -> list[MaxClique]: ...
    def child_copy(self, deep: bool = ...) -> MaxClique: ...
    def warmstart(self) -> MaxClique: ...
