from typing import TypeVar

from bnbpy.cython.manager import BaseNodeManager
from bnbpy.cython.node import Node
from bnbpy.cython.problem import Problem

P = TypeVar('P', bound=Problem)

class PriorityManagerInterface(BaseNodeManager[P]):
    """Priority queue manager backed by a native C++ binary heap.

    Nodes are stored with ``vector[double]`` priorities; the queue behaves
    as a *min*-heap (smallest priority dequeued first).

    Subclasses must override :meth:`make_priority`.
    """

    enqueue_time: float
    dequeue_time: float

    def size(self) -> int: ...
    def not_empty(self) -> bool: ...
    def enqueue(self, node: Node[P]) -> None: ...
    def enqueue_all(self, nodes: list[Node[P]]) -> None: ...
    def dequeue(self) -> Node[P] | None: ...
    def get_lower_bound(self) -> Node[P] | None: ...
    def pop_lower_bound(self) -> Node[P] | None: ...
    def filter_by_lb(self, max_lb: float) -> None: ...
    def clear(self) -> None: ...
    def pop_all(self) -> list[Node[P]]: ...
    def reset_timers(self) -> None:
        """Reset ``enqueue_time`` and ``dequeue_time`` to zero."""
        ...

    def peek_lb(self) -> float: ...
    def get_bound_nodes(self) -> set[Node[P]]: ...
    def make_priority(self, node: Node[P]) -> list[float]:
        """Return the ordering key for *node* as a list of floats.

        Must be overridden in subclasses.  Smaller values are dequeued first.
        """
        ...

class BestFirstSearch(PriorityManagerInterface[P]):
    """Best-first variant: priority ``(lb, -level, -index)``."""

    def make_priority(self, node: Node[P]) -> list[float]: ...
